### ISSUE TITLE
Auto Crystal Rewrite cuases me to get disconnected

### ISSUE THREAD

**Issue by MrLucaIsCool** [KassuK1/BlackOut#13]
Hi, ive been told to report it to the addon dev, but whenever i turn on auto crystal rewrite i get disconnected from the server im playing, ive tried turning down the crystal placement too see if that chnages anything but it doesnt, im also on mac if that may be an issue i dont really know (see image below for more info) also whenever im at spawn on this server (its 6b6t an anarchy server) which is really big and has lot of build everwhere my game crashes and i get 255 error code on the launcher.
<img width="1440" alt="Screen Shot 2023-03-25 at 1 11 19 pm" src="https://user-images.githubusercontent.com/128819126/227688877-5041b4a5-6410-4c65-b6d7-ce85d6f42fe0.png">

**Comment by MrLucaIsCool** [comment]
I have tried searching for answers online but can't find anyone else having the same issue, if this is something like a simple error, please tell me the solution i can use. King regards Luca

**Comment by CrytoPal** [comment]
Does it crash only on 6b or any server? And also send your latest log.

**Comment by OLEPOSSU** [comment]
are you on blackout latest build or latest release, which mc version, which meteor version and do u have any other mods

**Comment by KassuK1** [comment]
it could just be 6b being ass in general also what launcher are you on
