### ISSUE TITLE
Add Step+

### ISSUE THREAD

**Issue by NCPUser** [KassuK1/BlackOut#28]
NoCheatPlus Check Step, Meteor Step No Bypassed NCP, Add Step+ Bypassed NCP (NoCheatPlus)

**Comment by diowz** [comment]
yes please

**Comment by NCPUser** [comment]
OLEPOSSU, add please 1.5 2.0 2.5 Block step and smooth timer

**Comment by diowz** [comment]
yes

**Comment by KassuK1** [comment]
added
