### ISSUE TITLE
Game crashes with newest version of Blackout

### ISSUE THREAD

**Issue by Stuntlover-TM** [KassuK1/BlackOut#40]
I'm using the newest version of Blackout (1.0.1), after adding it to my mods folder and launching the game (fabric 1.20) it crashes after a few seconds, can't even launch, but no fabric error or anything like that. (without blackout it works fine)

**Comment by NCPUser** [comment]
1.20.1 use?

**Comment by NCPUser** [comment]
use 1.20.1 for fix

**Comment by KassuK1** [comment]
Blackout only works on 1.20.1 use the meteor dev build
