### ISSUE TITLE
Updating to version 1.20.1 as soon as possible please.

### ISSUE THREAD

**Issue by Python9874** [KassuK1/BlackOut#47]
Everyone wants meteor client addons to support 1.20.1. Would you mind updating it to 1.20.1 the jar file so if i'm on Meteor version 1.20.1 it is compatible with fabric. Thanks alot: Seb!

**Comment by KassuK1** [comment]
The development builds have been compatible with version 1.20.1 for a long time. But we have not made a new release due to us not having finished the changes we want to do before the next release.
