### ISSUE TITLE
Add better hud elements please 

### ISSUE THREAD

**Issue by KlyntarX69** [KassuK1/BlackOut#49]
ok lets get to the point so you added the cat girl element but I need more. MORE right now please I need my anime girls on my screen 
which means **On my hud** Idc if you added nudes

**Comment by KassuK1** [comment]
no haram
![haram](https://github.com/KassuK1/BlackOut/assets/100782510/ec04b7cc-acd7-4575-8ff5-7998a7e2d559)

**Comment by KlyntarX69** [comment]
PLease PLEASER PLEA SE PLEASAE PALSEAPLA EPLLASE ,sdkfmnasmdfnasdmfadf,
