### ISSUE TITLE
update to 1.20.4

### ISSUE THREAD

**Issue by ModxVoldHunter** [KassuK1/BlackOut#56]
that is the latest version

**Comment by Anonimouze** [comment]
Yes

**Comment by Error11O** [comment]
https://github.com/Error11O/BlackOut half assed job but works next commit will allow future to work with it

**Comment by NCPUser** [comment]
> https://github.com/Error11O/BlackOut half assed job but works next commit will allow future to work with it

add autobulid (action) for users

**Comment by Error11O** [comment]
@NCPUser build the 1st commit i sent and rotations and placing should work on my seccond commit is my fix for future to work with it.

**Comment by pixo2000** [comment]
jo this was almost 2 months ago. when update?

**Comment by ModxVoldHunter** [comment]
> jo this was almost 2 months ago. when update?

check dev build in releases

its slowly getting there
